# Generated by Django 4.2.6 on 2023-11-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickupibero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenitem',
            name='parentItem',
            field=models.IntegerField(null=True),
        ),
    ]
