# Generated by Django 4.2.6 on 2023-11-29 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickupibero', '0003_alter_ordenitem_parentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenitem',
            name='parentItem',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RelacionToppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowable_toppings', to='pickupibero.producto')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_on_products', to='pickupibero.producto')),
            ],
        ),
    ]
