# Generated by Django 4.2.6 on 2023-11-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickupibero', '0006_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/productos/img/'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='ubicacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
